version: "3.9"
services:
  cctv-app:
    build: .
    container_name: cctv_app
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - TELEGRAM_CHAT=${TELEGRAM_CHAT:-}
      - TRACKER=${TRACKER:-deepsort}   # set to 'bytetrack' to use ByteTrack (install required)
      - UPLOAD_METHOD=${UPLOAD_METHOD:-}
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"   # optional
    volumes:
      - ./recordings:/app/recordings
      - ./evidencias:/app/evidencias
      - ./reports:/app/reports
      - ./people.db:/app/people.db
      - ./config_history:/app/config_history
      - ./faces:/app/faces
      - ./cameras.json:/app/cameras.json

  cctv-reporter:
    build: .
    container_name: cctv_reporter
    restart: unless-stopped
    depends_on:
      - cctv-app
    entrypoint: ["bash","-c","while true; do python reporter.py once; sleep 28800; done"]
    volumes:
      - ./reports:/app/reports
      - ./people.db:/app/people.db