version: "3.9"

services:
  cctv-app:
    build: .
    container_name: cctv_app
    restart: unless-stopped
    volumes:
      - ./recordings:/app/recordings
      - ./evidencias:/app/evidencias
      - ./reports:/app/reports
      - ./config_history:/app/config_history
      - ./faces:/app/faces
      - ./people.db:/app/people.db
      - ./cameras.json:/app/cameras.json
    ports:
      - "5000:5000"   # API Flask
      - "5900:5900"   # (opcional si usas VNC para PyQt en contenedor)

  cctv-reporter:
    build: .
    container_name: cctv_reporter
    restart: unless-stopped
    command: ["python", "reporter.py"]
    volumes:
      - ./reports:/app/reports
      - ./people.db:/app/people.db

volumes:
  recordings:
  evidencias:
  reports:
  config_history:
  faces: